# Generated by Django 4.0.3 on 2022-04-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikuapp', '0002_alter_category_options_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='haiku',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='haiku_theme',
            field=models.CharField(choices=[('', '---------'), ('human nature', 'human nature'), ('nature and seasons', 'nature and seasons'), ('others', 'others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='entry_status',
            name='entry_status',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
